#!/usr/bin/env python3
import sys

def generate_marker_sdf(x=-533, y=165.0, z=0.0, radius=5.0, length=2.0,
                        r=0, g=1, b=0, a=0.5,
                        filename="/home/antoni/gazebo_maritime_ws/src/gazebo_maritime/worlds/markers.sdf"):
    sdf_content = f"""

<!-- Autogenerated file by src/autpilot/autopilot/add_markers.py to visualize checkpoints -->

<?xml version="1.0" ?>

<sdf version="1.9">
<model name="marker_cylinder">
    <pose>{x} {y} {z} 0 0 0</pose>
    <static>true</static>
    <link name="link">
    <visual name="visual">
        <geometry>
        <cylinder>
            <radius>{radius}</radius>
            <length>{length}</length>
        </cylinder>
        </geometry>
        <material>
        <ambient>{r} {g} {b} {a}</ambient>
        <diffuse>{r} {g} {b} {a}</diffuse>
        </material>
    </visual>
    </link>
</model>
</sdf>
"""
    with open(filename, "w") as f:
        f.write(sdf_content)
    print(f"File '{filename}' generated!")

if __name__ == "__main__":
    generate_marker_sdf()
